### ISSUE TITLE
Improve already-present performance in computeIfAbsent, putIfAbsent

### ISSUE THREAD

**Issue by squallliu** [AdoptOpenJDK/openjdk-jdk8u#21]
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8161372

http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/main/java/util/concurrent/ConcurrentHashMap.java?r1=1.295&r2=1.296

**Comment by karianna** [comment]
Backport requests should be made upstream at openjdk.java.net (search for the jdk8u mailing list!).
