### ISSUE TITLE
Broken link in OpenJDK8U-jdk_x64_linux_hotspot_8u292b10.tar.gz

### ISSUE THREAD

**Issue by ghost** [AdoptOpenJDK/openjdk-jdk8u#23]
Hello,
the published tarball at https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_linux_hotspot_8u292b10.tar.gz (linked from https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot) contains a broken link:
`jdk8u292-b10/jre/lib/amd64/server/libjsig.debuginfo -> ../libjsig.debuginfo`

`jdk8u292-b10/jre/lib/amd64/libjsig.debuginfo` as target is missing or the link should be removed.

This leads to errors when building own rpms.

**Comment by karianna** [comment]
This has been fixed in the Adoptium builds scripts.  TBD on respinning a release or waiting for an Eclipse Adoptium release.
