### ISSUE TITLE
Repo was not synced since May

### ISSUE THREAD

**Issue by mblauth** [AdoptOpenJDK/openjdk-jdk8u#28]
It seems the repo was not synced in a while. The newest tag is still jdk8u302-b4 (pre -ga). It looks as if the sync script ran last in May.

**Comment by karianna** [comment]
We've moved to adoptium.net so github.com/adoptium/openjdk-jdk8u

**Comment by Marcono1234** [comment]
The correct link appears to be https://github.com/adoptium/jdk8u

Would it be possible to indicate this here more clearly? I assume you cannot (or don't want to) alter the README, but could you maybe do one, or all of these things:
- Archive the repository
- [Pin](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository) this or a separate GitHub issue
- Update the "About" section of this GitHub repository to point to the new repo (though personally I think the "About" section is easy to overlook)

(Possibly applying this to the other JDK mirror repositories as well, if you think this is necessary)
