### ISSUE TITLE
jdk.serial filter is not working for restricting depth of treemap in java

### ISSUE THREAD

**Issue by kgcorner** [AdoptOpenJDK/openjdk-jdk8u#5]
[JEP 290 ](https://openjdk.java.net/jeps/290) solves the problem of deserialization vulnerabilities except some collection classes which includes TreeMap and LinkedList.

Can we have any solution or any work around to counter that?
 

In our RMI interface we are accepting Objects which may have TreeMap and since there's no check on the size of treemap it is vulnerable to DDos Attack. We have solution for ArrayList, Hashmap etc, Can we have something similar for TreeMap and LinkedList as well?

**Comment by karianna** [comment]
@kgcorner This is a question best for the core-libs-dev mailing list at openjdk.java.net
